from fastapi import FastAPI
from app.core.database import Base, engine
from app.infrastructure.orm.table_registry import TABLE_NAMES, create_tables
from app.interfaces.api.table_router import create_table_router
from app.interfaces.api import (
    appgroupuser,
    appotor,
    approle,
    appuser,
    dynamic_records,
    jnshist,
    jnsjr,
    jnskatkendaraan,
    jnskendaraan,
    jnsmilik,
    jnsstrurek,
    jnspajak,
    jnsplat,
    jnsprogresif,
    jnsranmor,
    jnstarif,
    jnsumum,
    mapjnspendapatan,
    masterab,
    masterabdet,
    masterbadan,
    masterbank,
    masterbbm,
    masterbendahara,
    masterflow,
    masterhapusdenda,
    masterhistory,
    masterjabttd,
    masterjnspendapatan,
    masterkabkota,
    masterkabkotaall,
    masterkaupt,
    masterkb,
    masterkbdet,
    masterkecamatan,
    masterkelurahan,
    masterkiosk,
    masterktp,
    masterlibur,
    mastermerk,
    masternpwpd,
    masterpegawai,
    masterprovinsi,
    masterrekd,
    masterreknrc,
    masterrt,
    masterrw,
    mastertarif,
    users,
)

Base.metadata.create_all(bind=engine)
create_tables()

app = FastAPI(
    title="Clean Architecture Users API",
    docs_url="/",
    redoc_url=None,
)

app.include_router(users.router)
app.include_router(dynamic_records.router)
app.include_router(appgroupuser.router)
app.include_router(appotor.router)
app.include_router(approle.router)
app.include_router(appuser.router)
app.include_router(jnshist.router)
app.include_router(jnsjr.router)
app.include_router(jnskatkendaraan.router)
app.include_router(jnskendaraan.router)
app.include_router(jnsmilik.router)
app.include_router(jnsstrurek.router)
app.include_router(jnspajak.router)
app.include_router(jnsplat.router)
app.include_router(jnsprogresif.router)
app.include_router(jnsranmor.router)
app.include_router(jnstarif.router)
app.include_router(jnsumum.router)
app.include_router(mapjnspendapatan.router)
app.include_router(masterab.router)
app.include_router(masterabdet.router)
app.include_router(masterbadan.router)
app.include_router(masterbank.router)
app.include_router(masterbbm.router)
app.include_router(masterbendahara.router)
app.include_router(masterflow.router)
app.include_router(masterhapusdenda.router)
app.include_router(masterhistory.router)
app.include_router(masterjabttd.router)
app.include_router(masterjnspendapatan.router)
app.include_router(masterkabkota.router)
app.include_router(masterkabkotaall.router)
app.include_router(masterkaupt.router)
app.include_router(masterkb.router)
app.include_router(masterkbdet.router)
app.include_router(masterkecamatan.router)
app.include_router(masterkelurahan.router)
app.include_router(masterkiosk.router)
app.include_router(masterktp.router)
app.include_router(masterlibur.router)
app.include_router(mastermerk.router)
app.include_router(masternpwpd.router)
app.include_router(masterpegawai.router)
app.include_router(masterprovinsi.router)
app.include_router(masterrekd.router)
app.include_router(masterreknrc.router)
app.include_router(masterrt.router)
app.include_router(masterrw.router)
app.include_router(mastertarif.router)

custom_table_routes = {
    "users",
    "dynamic_records",
    "appgroupuser",
    "appotor",
    "approle",
    "appuser",
    "jnshist",
    "jnsjr",
    "jnskatkendaraan",
    "jnskendaraan",
    "jnsmilik",
    "jnsstrurek",
    "jnspajak",
    "jnsplat",
    "jnsprogresif",
    "jnsranmor",
    "jnstarif",
    "jnsumum",
    "mapjnspendapatan",
    "masterab",
    "masterabdet",
    "masterbadan",
    "masterbank",
    "masterbbm",
    "masterbendahara",
    "masterflow",
    "masterhapusdenda",
    "masterhistory",
    "masterjabttd",
    "masterjnspendapatan",
    "masterkabkota",
    "masterkabkotaall",
    "masterkaupt",
    "masterkb",
    "masterkbdet",
    "masterkecamatan",
    "masterkelurahan",
    "masterkiosk",
    "masterktp",
    "masterlibur",
    "mastermerk",
    "masternpwpd",
    "masterpegawai",
    "masterprovinsi",
    "masterrekd",
    "masterreknrc",
    "masterrt",
    "masterrw",
    "mastertarif",
}

for table_name in TABLE_NAMES:
    if table_name in custom_table_routes:
        continue
    app.include_router(create_table_router(table_name))
