from datetime import date
from typing import List

from app.domain.entities.masterwp import MasterWp
from app.domain.repositories.masterwp_repository import MasterWpRepository


class MasterWpUseCase:

    def __init__(self, repository: MasterWpRepository):
        self.repository = repository

    def get_all(
        self,
        filters: dict | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> List[MasterWp]:
        return self.repository.get_all(filters=filters, page=page, limit=limit)

    def get_by_id(self, idwp: int) -> MasterWp | None:
        return self.repository.get_by_id(idwp)

    def create(
        self,
        objekbadanno: str,
        namabadan: str,
        insidentil: str,
        nopollama: str,
        kdplat: str,
        idgroupusaha: str | None = None,
        kodepolisi: str | None = None,
        kodelokasi: str | None = None,
        idbadan: int | None = None,
        idklasifikasi: str | None = None,
        idlokasi: str | None = None,
        alamat: str | None = None,
        idkabkokta: int | None = None,
        idkecamatan: int | None = None,
        idkelurahan: int | None = None,
        idrw: int | None = None,
        idrt: int | None = None,
        telepon: str | None = None,
        fax: str | None = None,
        namapemilik: str | None = None,
        idktp: int | None = None,
        pekerjaan: str | None = None,
        tgldaftar: date | None = None,
        tglsah: date | None = None,
        keteblokir: str | None = None,
        tglhapus: date | None = None,
        groupblokir: str | None = None,
        lastskp: str | None = None,
        jnskendid: str | None = None,
        idmerk: int | None = None,
        merk: str | None = None,
        tipe: str | None = None,
        tahunbuat: int | None = None,
        kodebbm: str | None = None,
        bbm: str | None = None,
        cylinder: int | None = None,
        norangka: str | None = None,
        nomesin: str | None = None,
        nobpkb: str | None = None,
        kdmilik: str | None = None,
        kdguna: str | None = None,
        kendke: int | None = None,
        warna: str | None = None,
        nostnkb: str | None = None,
        daftarstnk: str | None = None,
        tglcetakstnk: date | None = None,
        tglstnk: date | None = None,
        sdstnk: date | None = None,
        tglskp: date | None = None,
        awalskp: date | None = None,
        akhirskp: date | None = None,
        tglmutasi: date | None = None,
        tgljualbeli: date | None = None,
        nodaftar: str | None = None,
        nosah1: str | None = None,
        tglsah1: date | None = None,
        nosah2: str | None = None,
        tglsah2: date | None = None,
        nosah3: str | None = None,
        tglsah3: date | None = None,
        nosah4: str | None = None,
        tglsah4: date | None = None,
        laporjual: date | None = None,
        nikpemilik: str | None = None,
        notelppemilik: str | None = None,
        putih: str | None = None,
        status: str | None = None,
        statint: str | None = None,
        created_by: str | None = None,
        updated_by: str | None = None,
    ) -> MasterWp:
        master_wp = MasterWp(
            idwp=None,
            objekbadanno=objekbadanno,
            namabadan=namabadan,
            insidentil=insidentil,
            nopollama=nopollama,
            kdplat=kdplat,
            idgroupusaha=idgroupusaha,
            kodepolisi=kodepolisi,
            kodelokasi=kodelokasi,
            idbadan=idbadan,
            idklasifikasi=idklasifikasi,
            idlokasi=idlokasi,
            alamat=alamat,
            idkabkokta=idkabkokta,
            idkecamatan=idkecamatan,
            idkelurahan=idkelurahan,
            idrw=idrw,
            idrt=idrt,
            telepon=telepon,
            fax=fax,
            namapemilik=namapemilik,
            idktp=idktp,
            pekerjaan=pekerjaan,
            tgldaftar=tgldaftar,
            tglsah=tglsah,
            keteblokir=keteblokir,
            tglhapus=tglhapus,
            groupblokir=groupblokir,
            lastskp=lastskp,
            jnskendid=jnskendid,
            idmerk=idmerk,
            merk=merk,
            tipe=tipe,
            tahunbuat=tahunbuat,
            kodebbm=kodebbm,
            bbm=bbm,
            cylinder=cylinder,
            norangka=norangka,
            nomesin=nomesin,
            nobpkb=nobpkb,
            kdmilik=kdmilik,
            kdguna=kdguna,
            kendke=kendke,
            warna=warna,
            nostnkb=nostnkb,
            daftarstnk=daftarstnk,
            tglcetakstnk=tglcetakstnk,
            tglstnk=tglstnk,
            sdstnk=sdstnk,
            tglskp=tglskp,
            awalskp=awalskp,
            akhirskp=akhirskp,
            tglmutasi=tglmutasi,
            tgljualbeli=tgljualbeli,
            nodaftar=nodaftar,
            nosah1=nosah1,
            tglsah1=tglsah1,
            nosah2=nosah2,
            tglsah2=tglsah2,
            nosah3=nosah3,
            tglsah3=tglsah3,
            nosah4=nosah4,
            tglsah4=tglsah4,
            laporjual=laporjual,
            nikpemilik=nikpemilik,
            notelppemilik=notelppemilik,
            putih=putih,
            status=status,
            statint=statint,
            created_by=created_by,
            updated_by=updated_by,
        )
        return self.repository.create(master_wp)

    def update(
        self,
        idwp: int,
        objekbadanno: str | None,
        namabadan: str | None,
        insidentil: str | None,
        nopollama: str | None,
        kdplat: str | None,
        idgroupusaha: str | None,
        kodepolisi: str | None,
        kodelokasi: str | None,
        idbadan: int | None,
        idklasifikasi: str | None,
        idlokasi: str | None,
        alamat: str | None,
        idkabkokta: int | None,
        idkecamatan: int | None,
        idkelurahan: int | None,
        idrw: int | None,
        idrt: int | None,
        telepon: str | None,
        fax: str | None,
        namapemilik: str | None,
        idktp: int | None,
        pekerjaan: str | None,
        tgldaftar: date | None,
        tglsah: date | None,
        keteblokir: str | None,
        tglhapus: date | None,
        groupblokir: str | None,
        lastskp: str | None,
        jnskendid: str | None,
        idmerk: int | None,
        merk: str | None,
        tipe: str | None,
        tahunbuat: int | None,
        kodebbm: str | None,
        bbm: str | None,
        cylinder: int | None,
        norangka: str | None,
        nomesin: str | None,
        nobpkb: str | None,
        kdmilik: str | None,
        kdguna: str | None,
        kendke: int | None,
        warna: str | None,
        nostnkb: str | None,
        daftarstnk: str | None,
        tglcetakstnk: date | None,
        tglstnk: date | None,
        sdstnk: date | None,
        tglskp: date | None,
        awalskp: date | None,
        akhirskp: date | None,
        tglmutasi: date | None,
        tgljualbeli: date | None,
        nodaftar: str | None,
        nosah1: str | None,
        tglsah1: date | None,
        nosah2: str | None,
        tglsah2: date | None,
        nosah3: str | None,
        tglsah3: date | None,
        nosah4: str | None,
        tglsah4: date | None,
        laporjual: date | None,
        nikpemilik: str | None,
        notelppemilik: str | None,
        putih: str | None,
        status: str | None,
        statint: str | None,
        updated_by: str | None,
    ) -> MasterWp | None:
        master_wp = MasterWp(
            idwp=idwp,
            objekbadanno=objekbadanno,
            namabadan=namabadan,
            insidentil=insidentil,
            nopollama=nopollama,
            kdplat=kdplat,
            idgroupusaha=idgroupusaha,
            kodepolisi=kodepolisi,
            kodelokasi=kodelokasi,
            idbadan=idbadan,
            idklasifikasi=idklasifikasi,
            idlokasi=idlokasi,
            alamat=alamat,
            idkabkokta=idkabkokta,
            idkecamatan=idkecamatan,
            idkelurahan=idkelurahan,
            idrw=idrw,
            idrt=idrt,
            telepon=telepon,
            fax=fax,
            namapemilik=namapemilik,
            idktp=idktp,
            pekerjaan=pekerjaan,
            tgldaftar=tgldaftar,
            tglsah=tglsah,
            keteblokir=keteblokir,
            tglhapus=tglhapus,
            groupblokir=groupblokir,
            lastskp=lastskp,
            jnskendid=jnskendid,
            idmerk=idmerk,
            merk=merk,
            tipe=tipe,
            tahunbuat=tahunbuat,
            kodebbm=kodebbm,
            bbm=bbm,
            cylinder=cylinder,
            norangka=norangka,
            nomesin=nomesin,
            nobpkb=nobpkb,
            kdmilik=kdmilik,
            kdguna=kdguna,
            kendke=kendke,
            warna=warna,
            nostnkb=nostnkb,
            daftarstnk=daftarstnk,
            tglcetakstnk=tglcetakstnk,
            tglstnk=tglstnk,
            sdstnk=sdstnk,
            tglskp=tglskp,
            awalskp=awalskp,
            akhirskp=akhirskp,
            tglmutasi=tglmutasi,
            tgljualbeli=tgljualbeli,
            nodaftar=nodaftar,
            nosah1=nosah1,
            tglsah1=tglsah1,
            nosah2=nosah2,
            tglsah2=tglsah2,
            nosah3=nosah3,
            tglsah3=tglsah3,
            nosah4=nosah4,
            tglsah4=tglsah4,
            laporjual=laporjual,
            nikpemilik=nikpemilik,
            notelppemilik=notelppemilik,
            putih=putih,
            status=status,
            statint=statint,
            updated_by=updated_by,
        )
        return self.repository.update(idwp, master_wp)

    def delete(self, idwp: int) -> bool:
        return self.repository.delete(idwp)
