from datetime import date
from typing import List

from app.domain.entities.masterktp import MasterKtp
from app.domain.repositories.masterktp_repository import MasterKtpRepository


class MasterKtpUseCase:

    def __init__(self, repository: MasterKtpRepository):
        self.repository = repository

    def get_all(self) -> List[MasterKtp]:
        return self.repository.get_all()

    def get_by_id(self, idktp: int) -> MasterKtp | None:
        return self.repository.get_by_id(idktp)

    def create(
        self,
        nik: str,
        nama: str,
        nohp: str,
        alamat: str,
        idkabkokta: int,
        idkecamatan: int,
        idkelurahan: int,
        agama: int | None = None,
        tgldaftar: date | None = None,
        idprovinsi: int | None = None,
        idrw: int | None = None,
        idrt: int | None = None,
        kdrt: str | None = None,
        nikah: int | None = None,
        tempatlahir: str | None = None,
        tgllahir: date | None = None,
        tglregistrasi: date | None = None,
        nokk: str | None = None,
        nobpjs: str | None = None,
        goldarah: str | None = None,
        email: str | None = None,
        pendidikan: str | None = None,
        jeniskelamin: str | None = None,
        dusun: str | None = None,
        pekerjaan: str | None = None,
        namaayah: str | None = None,
        namaibu: str | None = None,
        negara: str | None = None,
        statwn: str | None = None,
        statint: str | None = None,
        tglint: date | None = None,
        ket: str | None = None,
        created_by: str | None = None,
        updated_by: str | None = None,
    ) -> MasterKtp:
        master_ktp = MasterKtp(
            idktp=None,
            nik=nik,
            nama=nama,
            nohp=nohp,
            alamat=alamat,
            idkabkokta=idkabkokta,
            idkecamatan=idkecamatan,
            idkelurahan=idkelurahan,
            agama=agama,
            tgldaftar=tgldaftar,
            idprovinsi=idprovinsi,
            idrw=idrw,
            idrt=idrt,
            kdrt=kdrt,
            nikah=nikah,
            tempatlahir=tempatlahir,
            tgllahir=tgllahir,
            tglregistrasi=tglregistrasi,
            nokk=nokk,
            nobpjs=nobpjs,
            goldarah=goldarah,
            email=email,
            pendidikan=pendidikan,
            jeniskelamin=jeniskelamin,
            dusun=dusun,
            pekerjaan=pekerjaan,
            namaayah=namaayah,
            namaibu=namaibu,
            negara=negara,
            statwn=statwn,
            statint=statint,
            tglint=tglint,
            ket=ket,
            created_by=created_by,
            updated_by=updated_by,
        )
        return self.repository.create(master_ktp)

    def update(
        self,
        idktp: int,
        nik: str | None,
        nama: str | None,
        nohp: str | None,
        alamat: str | None,
        idkabkokta: int | None,
        idkecamatan: int | None,
        idkelurahan: int | None,
        agama: int | None,
        tgldaftar: date | None,
        idprovinsi: int | None,
        idrw: int | None,
        idrt: int | None,
        kdrt: str | None,
        nikah: int | None,
        tempatlahir: str | None,
        tgllahir: date | None,
        tglregistrasi: date | None,
        nokk: str | None,
        nobpjs: str | None,
        goldarah: str | None,
        email: str | None,
        pendidikan: str | None,
        jeniskelamin: str | None,
        dusun: str | None,
        pekerjaan: str | None,
        namaayah: str | None,
        namaibu: str | None,
        negara: str | None,
        statwn: str | None,
        statint: str | None,
        tglint: date | None,
        ket: str | None,
        updated_by: str | None,
    ) -> MasterKtp | None:
        master_ktp = MasterKtp(
            idktp=idktp,
            nik=nik,
            nama=nama,
            nohp=nohp,
            alamat=alamat,
            idkabkokta=idkabkokta,
            idkecamatan=idkecamatan,
            idkelurahan=idkelurahan,
            agama=agama,
            tgldaftar=tgldaftar,
            idprovinsi=idprovinsi,
            idrw=idrw,
            idrt=idrt,
            kdrt=kdrt,
            nikah=nikah,
            tempatlahir=tempatlahir,
            tgllahir=tgllahir,
            tglregistrasi=tglregistrasi,
            nokk=nokk,
            nobpjs=nobpjs,
            goldarah=goldarah,
            email=email,
            pendidikan=pendidikan,
            jeniskelamin=jeniskelamin,
            dusun=dusun,
            pekerjaan=pekerjaan,
            namaayah=namaayah,
            namaibu=namaibu,
            negara=negara,
            statwn=statwn,
            statint=statint,
            tglint=tglint,
            ket=ket,
            updated_by=updated_by,
        )
        return self.repository.update(idktp, master_ktp)

    def delete(self, idktp: int) -> bool:
        return self.repository.delete(idktp)
