from datetime import date
from typing import List

from app.domain.entities.masterkb import MasterKb
from app.domain.repositories.masterkb_repository import MasterKbRepository


class MasterKbUseCase:

    def __init__(self, repository: MasterKbRepository):
        self.repository = repository

    def get_all(self) -> List[MasterKb]:
        return self.repository.get_all()

    def get_by_id(self, idkb: int) -> MasterKb | None:
        return self.repository.get_by_id(idkb)

    def create(
        self,
        namabadan: str,
        insidentil: str,
        kdplat: str,
        nomorfaktur: str | None = None,
        alamat: str | None = None,
        idkabkokta: int | None = None,
        idkecamatan: int | None = None,
        idkelurahan: int | None = None,
        idrw: int | None = None,
        idrt: int | None = None,
        telepon: str | None = None,
        fax: str | None = None,
        idktp: int | None = None,
        noktp: str | None = None,
        pekerjaan: str | None = None,
        tgldaftar: date | None = None,
        tglfaktur: date | None = None,
        jnskendid: str | None = None,
        idmerk: int | None = None,
        merk: str | None = None,
        tipe: str | None = None,
        tahunbuat: int | None = None,
        kodebbm: str | None = None,
        bbm: str | None = None,
        cylinder: int | None = None,
        norangka: str | None = None,
        nomesin: str | None = None,
        nobpkb: str | None = None,
        kdmilik: str | None = None,
        kdguna: str | None = None,
        kendke: int | None = None,
        warna: str | None = None,
        created_by: str | None = None,
        updated_by: str | None = None,
    ) -> MasterKb:
        master_kb = MasterKb(
            idkb=None,
            namabadan=namabadan,
            insidentil=insidentil,
            kdplat=kdplat,
            nomorfaktur=nomorfaktur,
            alamat=alamat,
            idkabkokta=idkabkokta,
            idkecamatan=idkecamatan,
            idkelurahan=idkelurahan,
            idrw=idrw,
            idrt=idrt,
            telepon=telepon,
            fax=fax,
            idktp=idktp,
            noktp=noktp,
            pekerjaan=pekerjaan,
            tgldaftar=tgldaftar,
            tglfaktur=tglfaktur,
            jnskendid=jnskendid,
            idmerk=idmerk,
            merk=merk,
            tipe=tipe,
            tahunbuat=tahunbuat,
            kodebbm=kodebbm,
            bbm=bbm,
            cylinder=cylinder,
            norangka=norangka,
            nomesin=nomesin,
            nobpkb=nobpkb,
            kdmilik=kdmilik,
            kdguna=kdguna,
            kendke=kendke,
            warna=warna,
            created_by=created_by,
            updated_by=updated_by,
        )
        return self.repository.create(master_kb)

    def update(
        self,
        idkb: int,
        namabadan: str | None,
        insidentil: str | None,
        kdplat: str | None,
        nomorfaktur: str | None,
        alamat: str | None,
        idkabkokta: int | None,
        idkecamatan: int | None,
        idkelurahan: int | None,
        idrw: int | None,
        idrt: int | None,
        telepon: str | None,
        fax: str | None,
        idktp: int | None,
        noktp: str | None,
        pekerjaan: str | None,
        tgldaftar: date | None,
        tglfaktur: date | None,
        jnskendid: str | None,
        idmerk: int | None,
        merk: str | None,
        tipe: str | None,
        tahunbuat: int | None,
        kodebbm: str | None,
        bbm: str | None,
        cylinder: int | None,
        norangka: str | None,
        nomesin: str | None,
        nobpkb: str | None,
        kdmilik: str | None,
        kdguna: str | None,
        kendke: int | None,
        warna: str | None,
        updated_by: str | None,
    ) -> MasterKb | None:
        master_kb = MasterKb(
            idkb=idkb,
            namabadan=namabadan,
            insidentil=insidentil,
            kdplat=kdplat,
            nomorfaktur=nomorfaktur,
            alamat=alamat,
            idkabkokta=idkabkokta,
            idkecamatan=idkecamatan,
            idkelurahan=idkelurahan,
            idrw=idrw,
            idrt=idrt,
            telepon=telepon,
            fax=fax,
            idktp=idktp,
            noktp=noktp,
            pekerjaan=pekerjaan,
            tgldaftar=tgldaftar,
            tglfaktur=tglfaktur,
            jnskendid=jnskendid,
            idmerk=idmerk,
            merk=merk,
            tipe=tipe,
            tahunbuat=tahunbuat,
            kodebbm=kodebbm,
            bbm=bbm,
            cylinder=cylinder,
            norangka=norangka,
            nomesin=nomesin,
            nobpkb=nobpkb,
            kdmilik=kdmilik,
            kdguna=kdguna,
            kendke=kendke,
            warna=warna,
            updated_by=updated_by,
        )
        return self.repository.update(idkb, master_kb)

    def delete(self, idkb: int) -> bool:
        return self.repository.delete(idkb)
